version: '3.4'

services:
  sql-server:
    image: gustavohrgomes/nerdstore-sql-server:latest
    container_name: nerdstore-sql-server-development
    build:
      context: ../sql
      dockerfile: ./Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Senha123!"
      ACCEPT_EULA: "Y"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-nerdstore-development
    ports:
      - "5672:5672"
      - "15672:15672"

  nerdstore-seq:
    image: datalust/seq:latest
    container_name: nerdstore-seq-development
    ports:
        - 5341:80
    environment:
        ACCEPT_EULA: "Y"

  web-mvc:
    image: gustavohrgomes/nerdstore-web-mvc-ecommerce:latest
    container_name: nerdstore-web-mvc
    build:
      context: ../src
      dockerfile: ./web/NSE.WebApp.MVC/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5070

  api-bff-compras:
    image: gustavohrgomes/nerdstore-api-bff-compras:latest
    container_name: nerdstore-api-bff-compras
    build:
      context: ../src
      dockerfile: ./api gateways/NSE.Bff.Compras/Dockerfile
    restart: always
    ports:
      - "5076:5076"
      - "7076:7076"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:7076;http://+:5076
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-cert.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq

  nerdstore-server:
    image: gustavohrgomes/nerdstore-server:latest
    container_name: nerdstore-server
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web-mvc