version: '3.4'

services:
  sql-server:
    image: gustavohrgomes/nerdstore-sql-server:latest
    container_name: nerdstore-sql-server
    build:
      context: ../sql
      dockerfile: ./Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Senha123!"
      ACCEPT_EULA: "Y"
    networks:
      - nerdstore


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-nerdstore
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "nerdstore"
      RABBITMQ_DEFAULT_PASS: "nerdstore"
    networks:
      - nerdstore
    

  nerdstore-seq:
    image: datalust/seq:latest
    container_name: nerdstore-seq
    ports:
        - 5341:80
    environment:
        ACCEPT_EULA: "Y"
    networks:
      - nerdstore

  nerdstore-server:
    image: gustavohrgomes/nerdstore-server:latest
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nerdstore

networks:
  nerdstore:
    external: true