name: Build

on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string
        description: "Path of the project to build"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore
        run: dotnet restore ${{ inputs.project-path }}
      
      - name: Build
        run: dotnet build --no-restore