name: carrinho-api-pull-request-workflow

on:
  pull_request:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

  build:
    uses: ./.github/workflows/build.yml
    with:
      project-path: src/services/NSE.Carrinho.API/NSE.Carrinho.API.csproj
      dotnet-version: 6.0.x
  
  run-tests:
    uses: ./.github/workflows/tests.yml
    with:
      test-project-path: tests/Services/NSE.Carrinho.API.Unit/NSE.Carrinho.API.Tests.Unit.csproj
