name: carrinho-api-push

on:
  push:
    branches: [main, develop]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: ./.github/workflows/build.yml
        with:
          project-path: src/services/NSE.Carrinho.API/NSE.Carrinho.API.csproj
          dotnet-version: 6.0.x
      
      - name: Tests
        uses: ./.github/workflows/tests.yml
        with:
          test-project-path: tests/Services/NSE.Carrinho.API.Unit/NSE.Carrinho.API.Tests.Unit.csproj

      - name: Build and push docker image
        uses: ./.github/workflows/push-image.yml
        with:
          context: ./src
          dockerfile-path: ./src/services/NSE.Carrinho.API/Dockerfile
          image-tag: gustavohrgomes/nerdstore-carrinho-api:latest
