name: push docker image

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
        description: "Dockerfile context"
      dockerfile-path:
        required: true
        type: string
        description: "Dockerfile path"
      image-tag: 
        required: true
        type: string
        description: "Docker image tag"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile-path }}
          push: true
          tags: ${{ inputs.image-tag }}