name: Tests

on:
  workflow_call:
    inputs:
      test-project-path:
        required: true
        description: "Path of the test project"
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Run Tests
        run: dotnet test ${{ inputs.test-project-path }}