name: Tests

on:
  workflow_call:
    inputs:
      pull-request:
        required: true
        type: boolean
      solution-path:
        required: false
        description: "Solution path to test"
        type: string
      runsettings-path:
        required: false
        description: "Path to runsettings.xml"
        type: string
        default: ""
      code-exclusions:
        description: "Files to exclude from coverage"
        type: string
        default: ""
      sonar-project-key:
        type: string
    secrets:
      sonar-token:
        required: true
        description: "Sonar Cloud Token configured in the repository"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu' # Alternative distribution options are available.

      # - name: Cache SonarCloud packages
      #   uses: actions/cache@v3
      #   with:
      #     path: ~\sonar\cache
      #     key: ${{ runner.os }}-sonar
      #     restore-keys: ${{ runner.os }}-sonar
          
      # - name: Cache SonarCloud scanner
      #   id: cache-sonar-scanner
      #   uses: actions/cache@v3
      #   with:
      #     path: .\.sonar\scanner
      #     key: ${{ runner.os }}-sonar-scanner
      #     restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarCloud Scan
        if: ${{ inputs.pull-request == false && inputs.code-exclusions != '' }}
        env:
          SONAR_TOKEN: ${{ secrets.sonar-token }}
          COVERAGE_REPORTS_DIR: ${{ github.workspace }}/TestResults
          CODE_EXCLUSIONS: ${{ inputs.code-exclusions }}
        run: |
          dotnet-sonarscanner begin \
          /k:${{ inputs.sonar-project-key }} \
          /o:"gustavohrgomes" \
          /d:sonar.login="$SONAR_TOKEN" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.coverage.exclusions="$CODE_EXCLUSIONS" \
          /d:sonar.cs.coveragePlugin=opencover \
          /d:sonar.cs.opencover.reportsPaths="$COVERAGE_REPORTS_DIR/**/*.opencover.xml"

      - name: Begin SonarCloud Scan
        if: ${{ inputs.pull-request == false && inputs.code-exclusions == '' }}
        env:
          SONAR_TOKEN: ${{ secrets.sonar-token }}
          COVERAGE_REPORTS_DIR: ${{ github.workspace }}/TestResults
          CODE_EXCLUSIONS: ${{ inputs.code-exclusions }}
        run: |
          dotnet-sonarscanner begin \
          /k:${{ inputs.sonar-project-key }} \
          /o:"gustavohrgomes" \
          /d:sonar.login="$SONAR_TOKEN" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.coverage.exclusions="$CODE_EXCLUSIONS" \
          /d:sonar.cs.coveragePlugin=opencover \
          /d:sonar.cs.opencover.reportsPaths="$COVERAGE_REPORTS_DIR/**/*.opencover.xml"

      - name: Begin SonarCloud Scan For Pull Request
        if: ${{ inputs.pull-request == true && inputs.code-exclusions != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.sonar-token }}
          COVERAGE_REPORTS_DIR: ${{ github.workspace }}/TestResults
        run: |
          dotnet-sonarscanner begin \
          /k:${{ inputs.sonar-project-key }} \
          /o:"gustavohrgomes" \
          /d:sonar.login="$SONAR_TOKEN" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.pullrequest.key=${{ github.event.pull_request.number }} \
          /d:sonar.pullrequest.base=${{ github.event.pull_request.base.ref }} \
          /d:sonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} \
          /d:sonar.coverage.exclusions="$CODE_EXCLUSIONS" \
          /d:sonar.cs.coveragePlugin=opencover \
          /d:sonar.cs.opencover.reportsPaths="$COVERAGE_REPORTS_DIR/**/*.opencover.xml"

      - name: Begin SonarCloud Scan For Pull Request
        if: ${{ inputs.pull-request == true && inputs.code-exclusions == '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.sonar-token }}
          COVERAGE_REPORTS_DIR: ${{ github.workspace }}/TestResults
        run: |
          dotnet-sonarscanner begin \
          /k:${{ inputs.sonar-project-key }} \
          /o:"gustavohrgomes" \
          /d:sonar.login="$SONAR_TOKEN" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.pullrequest.key=${{ github.event.pull_request.number }} \
          /d:sonar.pullrequest.base=${{ github.event.pull_request.base.ref }} \
          /d:sonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} \
          /d:sonar.cs.coveragePlugin=opencover \
          /d:sonar.cs.opencover.reportsPaths="$COVERAGE_REPORTS_DIR/**/*.opencover.xml"

      - name: Restore Dependencies
        run: dotnet restore ${{ inputs.solution-path }}

      - name: Build Application
        run: dotnet build ${{ inputs.solution-path }} --no-restore

      - name: Run Tests
        #if: ${{ inputs.runsettings-path != '' }}
        env:
          COVERAGE_REPORTS_DIR: ${{ github.workspace }}/TestResults
          #RUN_SETTINGS: ${{ inputs.runsettings-path }}
          SOLUTION_PATH: ${{ inputs.solution-path}}
        run: |
          dotnet test $SOLUTION_PATH \
          --collect:"XPlat Code Coverage;Format=opencover" \
          --results-directory:"$COVERAGE_REPORTS_DIR/" \
        # --settings $RUN_SETTINGS

      # - name: Run Integration Tests
      #   if: ${{ inputs.integration-test-project != '' }}
      #   env:
      #     COVERAGE_REPORTS_DIR: ${{ github.workspace }}/TestResults
      #     TEST_PROJECT: ${{ inputs.integration-test-project }}
      #   run: |
      #     dotnet test $TEST_PROJECT \
      #     --collect:"XPlat Code Coverage" \
      #     --results-directory:"$COVERAGE_REPORTS_DIR/"

      - name: End SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.sonar-token }}
        run: dotnet-sonarscanner end /d:sonar.login="$SONAR_TOKEN"